# Workflow to build and deploy designer dashboard to server.
name: OpenGameData Event Monitor API Release
on:
  workflow_dispatch: # Allow manual trigger of this workflow from the Actions tab
  push: # Trigger automatically when we do a merge to production
    branches: [ production ]
    paths:
    - '.github/workflows/monitorAPI_CI.yml'
    - 'shared/**'
    - 'apps/monitor/**'

env:
  CI: ""
  DEPLOY_HOST: ${{ vars.OGD_MONITOR_HOST }}
  DEPLOY_DIR:  ${{ vars.WSGI_PATH }}/${{ github.event.repository.name }}/${{ github.ref_name }}/monitor
  DEPLOY_URL:  ${{ vars.OGD_MONITOR_HOST }}/${{ github.event.repository.name }}/${{ github.ref_name }}/monitor
  URL_PATH:    ${{ github.event.repository.name }}/${{ github.ref_name }}/monitor

jobs:
  release_deploy:
    name: Release Deploy of Monitor API
    runs-on: ubuntu-22.04
    steps:

  # 1. Local checkout & config
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

  # 2. Build 

  # 3. Remote config & deploy
    - name: Get OpenConnect installed
      run: sudo apt-get -q update && sudo apt-get -q install openconnect
    - name: Connect VPN
      run: echo ${{ secrets.VPN_PASS }} | sudo openconnect --protocol=gp -u ${{ secrets.VPN_USER }} --passwd-on-stdin soe.vpn.wisc.edu &

    - name: Setup Access Key
      run: |
        mkdir -p ~/.ssh
        echo '${{secrets.DEPLOY_KEY}}' >> ./key.txt
        chmod 600 ./key.txt
    - name: Ensure directory exists
      run: ssh -o StrictHostKeyChecking=no -T -i ./key.txt ${{ secrets.DEPLOY_USER }}@${{ env.DEPLOY_HOST }} "mkdir -p ${{ env.DEPLOY_DIR }}"

    - name: Upload *App* to web server via rsync
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -vrc --exclude-from rsync-exclude
        path: apps/monitor/*
        remote_path: ${{ env.DEPLOY_DIR }}
        remote_host: ${{ env.DEPLOY_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key:  ${{ secrets.DEPLOY_KEY  }}

  # 4. Cleanup & complete
    - name: Trigger service restart
      run: ssh -o StrictHostKeyChecking=no -T -i ./key.txt ${{ secrets.DEPLOY_USER }}@${{ env.DEPLOY_HOST }} "sudo systemctl restart monitor-api"
    - name: Announce deploy
      run: echo "Deployed to ${{ env.DEPLOY_URL }}"
    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ./*.log
